on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - dev
    
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            node_version: ['16']
            os: [ubuntu-latest, windows-latest, macOS-latest]
            
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
    - uses: actions/setup-node@v3
    - with:
        node-version: ${{ matrix.node_version }}
        
    - name: npm install and format
      run: |
        npm install
        npm run lint:backend
        npm run lint:frontend
