on:
    push:
        branches:
            - staging
            - dev
    pull_request:
        branches:
            - dev
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: "Test scenario tags"
                required: false
                type: boolean
            environment:
                description: "Environment to run tests against"
                type: environment
                required: true

jobs:
    test:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ["16"]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Install and Format
              run: |
                  echo ""
                  echo "Installing dependencies..."
                  npm install
                  echo ""
                  echo "Formatting backend..."
                  npm run lint:backend
                  echo ""
                  echo "Formatting frontend..."
                  npm run lint:frontend
