name: CI Testing
on:
    push:
        branches:
            - staging
            - main
    pull_request:
        branches:
            - dev
            - staging
            - main

jobs:
    test:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ["16"]
                os: [ubuntu-latest, windows-latest, macos-latest]
        # * replace with env vars and secrets, continue to update going forward
        # env/with:
        #   DB_URL: ${{ secrets.DB_URL }}
        environment: test
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Install
              run: |
                  echo ""
                  echo "📥 Installing dependencies..."
                  npm install
                  echo ""
                  echo "🛠️ Building Prisma..."
                  npm run build:prisma
                  echo ""
                  echo "🧱 Generating Prisma schema..."
                  npm run generate
            - name: Format and Lint
              run: |
                  echo ""
                  echo "🧹 Formatting..."
                  npm run format
                  echo "🧼 Linting..."
                  npm run lint
            - name: Test
              run: |
                  echo ""
                  echo "🔬 Testing backend API..."
                  echo ""
                  echo "⏳ Please hold. This might take a while..."
                  npm test
